# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown

title: OpenWhere Blog
description: Cloud Infrastructure and Software Engineering

authors:
  aaslinger:
    name: Andrew Aslinger
    email: aaslinger@openwhere.com
    github: owaaa
    gravatar: 
    linkedin: andrewaslinger
    bio: Senior Systems Architect
    gravatar: e8d3d442930c600d69a6e8ae254bb0e01
  apierce:
    name: Andrew Pierce
    bio: Senior Software Engineer
    email: apierce@openwhere.com
    github: owap
    gravatar: bdf3b5e10d7fb891416672504cadb19c
  sample:
    name: dbyll
    email: dbyll@ismaildemirbilek.com
    github: dbtek
    twitter: dbtek
    pinterest: asd123
    linkedin: asd123
    bio: Your stylish, minimalist theme!
    gravatar: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
