# Site settings
title: OpenWhere Blog
email: info@openwhere.com
description: > # this means to ignore newlines until "baseurl:"
  Cloud Infrastructure and Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openwhere.github.io" # the base hostname & protocol for your site
github_username:  OpenWhere

# Build settings
markdown: kramdown

# Blog Authors
authors:
  pierce:
    display_name: Andrew Pierce
    gravatar: 2804c426e5299c39cace93b8baf638ce
    email: apierce@openwhere.com
